server:
 port: 9006

spring:
 data:
  mongodb:
   uri: mongodb://localhost:27017/chatapp
  redis:
   port: ${REDIS_PORT:6379}
   host: ${REDIS_URL:localhost}
   password: ${REDIS_PASSWORD:1234}
   username: ${REDIS_USER:root}
 jackson:
  serialization:
   write-dates-as-timestamps: false

logging:
 level:
  org.springframework.web: DEBUG
  org.springframework.messaging: DEBUG

# STOMP ??? ??? ?? ?? (??)
management:
 endpoints:
  web:
   exposure:
    include: "*"
