server:
 port: 9006

spring:
 data:
  mongodb:
   uri: mongodb://localhost:27017/chatapp
  redis:
   port: 6379
   host: localhost
 jackson:
  serialization:
   write-dates-as-timestamps: false

logging:
 level:
  org.springframework.web: DEBUG
  org.springframework.messaging: DEBUG

# STOMP ??? ??? ?? ?? (??)
management:
 endpoints:
  web:
   exposure:
    include: "*"

jwt:
 issuer: dlstlr1707@gmail.com
 secret_key: 55DQ7XtZjKEuftetbQMtw0geU9SS1rR/fbrPOAqIQ2UUPJ+crjXRoLppDtreyvim53v3U6+hTLcbunHlxlNGlA==
