apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      nodeSelector:
        role: websocket
      containers:
        - name: chat-service
          image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/chat-service:latest
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          resources:
            requests:
              cpu: "400m"
              memory: "600Mi"
            limits:
              cpu: "700m"
              memory: "1024Mi"
          ports:
            - containerPort: 9006
          env:
            - name: MONGO_URL
              value: mongodb://$MONGODB_IP:27017/chatapp
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_URL
              value: $REDIS_IP
            - name: SPRING_PROFILES_ACTIVE
              value: deploy
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-service-secrets
                  key: REDIS_PASSWORD
            - name: REDIS_USER
              valueFrom:
                secretKeyRef:
                  name: chat-service-secrets
                  key: REDIS_USER
