apiVersion: v1
kind: Service
metadata:
  name: chat-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ws.himedia-a.com.
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ${AWS_CERTIFICATE_FRONT}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
spec:
  type: LoadBalancer
  selector:
    app: chat-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9006
    - name: https
      protocol: TCP
      port: 443
      targetPort: 9006